### ISSUE TITLE
BlinkyCpp_TemporaryKey.pfx is expired 

### ISSUE THREAD

**Issue by jceven** [ms-iot/adafruitsample#16]
Visual Studio complains the certificate is not valid when trying to deploy the project to remote (Raspberry Pi with IoT Core Win 10).  Certificate Manager shows the certificate expired on 12/5/15.  I don't know how to generate or pull in a new cert on Windows/Visual Studio so if you guys could generate a new one that's valid with the same name that would be appreciate.

**Comment by IoTGirl** [comment]
Hi @jceven ,
My apologies for the delay in response.  I am closing this issue as it has been more than a year but should you see this error with the latest image and toolset please reopen this issue and provide steps on how we might see the error.
Sincerely,
IoTGirl
